### ISSUE TITLE
HW1 Feedback

### ISSUE THREAD

**Issue by jvictorchen** [cskksdfklpz/baruch-mfe-python-summer#1]
* Since you're using `register_line_cell_magic`, it's possible that both line and cell are not None. In that case the code would miss the words in the line. 
* Profiling: Your list comprehension is actually slower. How did you come up with the conclusion? The list is too short and %time is too subject to randomness. Try larger list and use %timeit?
* Prime: 
  * `True if a%factor == 0 else False`. This is same as `a % factor`. 
  * You can use `all()` instead of `sum()` for early exit.
* Vector:
  * `len` is a keyword and should not be used as a variable name.
  * `__init__` can be simplified. No need to convert tuple into list. Tuple is actually better. And if you want to use list, use `self.container = list(args)` instead of the for loop.
  * `__repr__`: can use `join` to simplify the code
  * `__add__`/`__sub__`/`__pow__`/`__mul__`: use list comprehension?
* Case insensitive dict:
  * `__init__` is not correct. Try `CaseInsensitive(a=3)`
  * The logic is wrong. See below. 
```
d = CaseInsensitiveDict() 
d['Abc'] = 4
'Abc' in d
```

Score: B

**Comment by cskksdfklpz** [comment]
Thank you for your feedback :)
